# Generated by Django 4.1.1 on 2022-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(to='tesla.tag'),
        ),
    ]
