# Generated by Django 4.1.1 on 2022-10-03 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tesla', '0004_car_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtocar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagtocar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
