# Generated by Django 4.1.1 on 2022-10-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesla', '0005_tagtocar_created_at_tagtocar_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.IntegerField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tesla.car')),
            ],
        ),
    ]
